### PR TITLE
Add license and purchase link to getting started

### PR DESCRIPTION
**Pull request by bmorcos**
**Motivation and context:**

There was no mention of a license or any links from which to by one, now there is.

**How long should this take to review?**

- Quick (less than 40 lines changed or changes are straightforward)

**Where should a reviewer start?**

Build the docs and take a look

**Types of changes:**

- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- N/A I have tested this with all supported devices.
- N/A I have added tests to cover my changes.
- N/A I have run the test suite locally and all tests passed.

**Still to do:**

### CODE REVIEW

**Comment by xchoo** [comment]
I'm wondering if we should change the "NengoFPGA License" page heading to something else to avoid confusion between that and the NengoFPGA board licenses?

**Comment by xchoo** [comment]
Or move it to a "Project information" group like in Nengo-DL?

**Comment by bmorcos** [comment]
I changed the software license heading... Unsure if we want to create a project section or not :/

**Comment by bmorcos** [comment]
I Made a new section like NengoDL, looks good!

**Pull request merged**
