### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by bmorcos**
**Motivation and context:**

- Add nengo-de1 and nengo-pynq to intersphinx
- Start using intersphinx references
- Fix line wrapping for text
- Rename docs and examples using hyphen

**Interactions with other PRs:**

Need to merge in nengo/nengo-de1#4 and nengo/nengo-pynq#5 first so we have correct file names (hyphens)

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Where should a reviewer start?**

Take a look at the `gh-pages-test` branch

**Types of changes:**

- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- N/A I have tested this with all supported devices.
- N/A I have added tests to cover my changes.
- N/A I have run the test suite locally and all tests passed.

**Still to do:**

- [x] Merge in nengo/nengo-de1#4
- [ ] Merge in nengo/nengo-pynq#5

### CODE REVIEW

**Comment by xchoo** [comment]
The docs are building without the formatting in the code blocks (see images) on my machine. Can you build it on yours and double check that it's doing it proper? 

image

**Comment by xchoo** [comment]
I also have the lists rendering weird (the spacing is expanded?)
image

**Comment by xchoo** [comment]
Ooooh. I figured out what was happening. Because the build failed half way through, it doesn't update the css, and also doesn't process the notebook example outputs. Once the build is passing again, this should no longer be an issue.

As a side note, all of the html files are still generated even though the sphinx command fails part way through, so we can still do a force push to `gh-pages`.

So we have two options:
- Force push the broken build to `gh-pages`.
- Comment out the offending intersphinx links, and push that to `gh-pages`

**Comment by xchoo** [comment]
Okay. I've gone through the docs and we can start with the forced push to `gh-pages`.

**Comment by bmorcos** [comment]
Commenting for reference, a version of the docs was manually published to allow the `nengo-de1` and `nengo-pynq` docs to build successfully; once those are published this PR will be merged and published via CI as normal.

**Pull request merged**
